### ISSUE TITLE
Ubuntu 16.04 setup issue

### ISSUE THREAD

**Issue by tdekeizer** [bpmconsultag/CUPS-PrintNode#1]
Hi,  firstly thankyou for developing this project.  We are looking to use this to setup remote printing from our applictaion running on Linux.  We have gone through the install and setup process as noted but we are having an issue running the 

/usr/local/bin/printnode/generate_printnode_queue.py

command.  We are getting this error:
Capabilities found!
Creating queue: PNTest
Traceback (most recent call last):
  File "/usr/local/bin/printnode/generate_printnode_queue.py", line 156, in <module>
    INPUT_SLOTS = ast.literal_eval("[ %s ]" % PRINTER_CAPABILITIES_DICT["InputSlots"])
KeyError: 'InputSlots'

Python version.  3.6.8
Ubuntu:  16.04

Can you advise ?

Cheers
Tony

**Comment by tdekeizer** [comment]
Here is the redacted capabilities output if required ....

['XXXXXX', 'XXXXXXXX', '{', '  "duplex": true,', '  "color": true,', '  "InputTrays": [', '    "auto",', '    "main",', '    "alternate",', '    "rear"', '  ],', '  "name": "EPSON_WF_7620_Series",', '  "id": XXXXXXX,', '  "computer": "XXXXXXX"', '}', '']
['  "computer": "XXXXXX"']

**Comment by tdekeizer** [comment]
It woudl seem the code is not parsing the output correctly ?

**Comment by G4bbix** [comment]
Hi Tony 

The parsing seems indeed to be broken. We recently had errors with the generic PrintNode PPD, which only were resolved once we used the vendor PPD. Since this script's only purpose is to create the queue inject the name of the PrintNode bins into the ppd. 
To temporarly work around this issue you can manually create the queue with the following command:
lpadmin -p {Queue name} -v printnode://{PrintNode printer ID} -E -P {Path to printnode.ppd}

If you need to access different trays you'll have to write the PrintNode tray names to the ppd manually. 

Cheers Gabe

**Comment by tdekeizer** [comment]
Thanks Gabe thats really helpful .. will do as you say :-)

**Comment by G4bbix** [comment]
Hi Toni

I have created a new release fixing some issues with the the generate_printnode_queue.py:
https://github.com/bpmconsultag/CUPS-PrintNode/releases/tag/1.2

Cheers
Gabe

**Comment by G4bbix** [comment]
Closed due to inactivity.
